export interface IApplicantCard {
    id: string,
    name: string,
    currentJob: string,
    location: string,
    email: string,
    phoneNumber: string,
    cvLink: string,
}

export const applicants: IApplicantCard[] = [
	{
		id: '1',
		name: "John Smith",
		currentJob: "Software Developer",
		location: "Remote",
		email: "john.smith@domain.com",
		phoneNumber: "07745777454",
		cvLink: "www.somelocation.com",
	},
	{
		id: '2',
		name: "Jack Daniels",
		currentJob: "Software Developer",
		location: "London",
		email: "jack.daniels@domain.com",
		phoneNumber: "07745777454",
		cvLink: "www.somelocation.com",
	},
	{
		id: '3',
		name: "Jim Beam",
		currentJob: "Software Developer",
		location: "Manchester",
		email: "jim.beam@domain.com",
		phoneNumber: "07745777454",
		cvLink: "www.somelocation.com",
	},
	{
		id: '4',
		name: "Sarah Jane",
		currentJob: "Software Developer",
		location: "Cardif",
		email: "sarah.jane@domain.com",
		phoneNumber: "07745777454",
		cvLink: "www.somelocation.com",
	},
	{
		id: '5',
		name: "Keith Richards",
		currentJob: "Software Developer",
		location: "Glasgow",
		email: "keith.richards@domain.com",
		phoneNumber: "07745777454",
		cvLink: "www.somelocation.com",
	},
	{
		id: '6',
		name: "Richie Blackmore",
		currentJob: "Software Developer",
		location: "Leeds",
		email: "richie.blackmore@domain.com",
		phoneNumber: "07745777454",
		cvLink: "www.somelocation.com",
	},
];
